# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='exposici',
            new_name='exposicion',
        ),
    ]
