# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20160621_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposicion',
            options={'verbose_name_plural': 'Exposiciones'},
        ),
    ]
