# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_auto_20160622_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposicion',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='grupo',
        ),
        migrations.AddField(
            model_name='exposicion',
            name='grupotemp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.Grupo'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='grupotemp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.Grupo'),
        ),
    ]
