# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
        ('clases', '0004_auto_20160623_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposicion',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo'),
        ),
    ]
