# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0005_auto_20160623_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exposicion',
            name='grupotemp',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='grupotemp',
        ),
    ]
