# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0006_auto_20160623_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorPreguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('primero', models.BooleanField(default=False)),
                ('ultimo', models.BooleanField(default=False)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Clase')),
                ('exposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Exposicion')),
                ('preguntador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Grupo')),
            ],
        ),
    ]
