# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0008_pregunta_mejor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contadorpreguntas',
            name='clase',
        ),
    ]
