# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0011_auto_20160626_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrante',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Integrante',
        ),
    ]
