# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0013_auto_20160627_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposicion',
            old_name='start_preg',
            new_name='start_ques',
        ),
    ]
