# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0015_auto_20160630_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadorpreguntas',
            name='preguntador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo', verbose_name='Grupo que pregunta'),
        ),
    ]
