# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0016_auto_20160704_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='tp',
            options={'ordering': ['nombre']},
        ),
    ]
