# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0017_auto_20160711_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tp',
            name='nuemero',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
