# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0021_auto_20160712_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposicion',
            options={'ordering': ['clase', 'grupo', 'tp'], 'verbose_name_plural': 'Exposiciones'},
        ),
    ]
