# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0022_auto_20160712_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='exposicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='clases.Exposicion'),
        ),
    ]
