# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0023_auto_20160713_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposicion',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposiciones', to='clases.Clase'),
        ),
    ]
