# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0026_auto_20160815_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposicion',
            options={'ordering': ['clase__fecha', 'grupo', 'tp'], 'verbose_name_plural': 'Exposiciones'},
        ),
    ]
