# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0027_auto_20160907_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposicion',
            options={'ordering': ['clase', 'grupo', 'tp'], 'verbose_name_plural': 'Exposiciones'},
        ),
    ]
