# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0028_auto_20160918_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['exposicion', 'grupo']},
        ),
        migrations.AlterIndexTogether(
            name='pregunta',
            index_together=set([('exposicion', 'grupo')]),
        ),
    ]
