# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0029_auto_20160918_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposicion',
            name='video',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exposicion',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='clase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exposiciones', to='clases.Clase'),
        ),
    ]
