# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='descripcion',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_carpeta_drive',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
