# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_auto_20160708_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='descripcion',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id_carpeta_drive',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
