# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_grupo_integrantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['-año', 'numero']},
        ),
    ]
