# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 03:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0006_auto_20160805_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoevaluacion_grupal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now, unique=True)),
                ('año', models.IntegerField()),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Criterio_evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=200)),
                ('autoevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Autoevaluacion_grupal')),
            ],
            options={
                'ordering': ['criterio'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, 'El voto no puede ser superior a 5'), django.core.validators.MinValueValidator(1, 'El voto no puede ser menor a 1')])),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Criterio_evaluacion')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluador', to='grupos.Grupo')),
                ('grupo_evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_evaluado', to='grupos.Grupo')),
            ],
        ),
    ]
