# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 02:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0007_autoevaluacion_grupal_criterio_evaluacion_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
