# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='autor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
