# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teoria', '0003_auto_20160723_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['-fecha']},
        ),
    ]
