# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teoria', '0004_auto_20160723_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['autor', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['autor', 'pregunta']},
        ),
    ]
