# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teoria', '0009_auto_20160815_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 8, 29, 4, 7, 13, 361778, tzinfo=utc)),
        ),
    ]
