# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 03:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('teoria', '0010_voto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2016, 8, 30, 3, 32, 37, 510158, tzinfo=utc)),
        ),
    ]
