# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teoria', '0011_auto_20160830_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
