# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0008_evaluacion_usuario'),
        ('teoria', '0012_auto_20160903_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='grupo_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_teoria', to='grupos.Grupo'),
        ),
    ]
