# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-26 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0008_evaluacion_usuario'),
        ('teoria', '0013_pregunta_grupo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='grupo_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_teoria', to='grupos.Grupo'),
        ),
    ]
