# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-26 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoria', '0014_material_grupo_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-vigente', 'orden', 'autor', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['-vigente', 'orden', 'autor', 'pregunta']},
        ),
        migrations.AddField(
            model_name='material',
            name='orden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
