# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-29 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoria', '0015_auto_20200426_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
