# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['edited']},
        ),
    ]
